name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'TesteCloud/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Criar o arquivo ZIP do código (dentro do runner temporário)
      - name: Zip Lambda code
        run: |
          zip -r deployment-package.zip .
        working-directory: ./TesteCloud
      
      # 2. Configurar Credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 3. Deploy da Função Lambda
      - name: Deploy Lambda function
        uses: aws-actions/aws-lambda-deploy@v1.1.0
        with:
          function-name: slackBotTests
          zip-file: ./TesteCloud/deployment-package.zip